config/routes.rb
Rails.application.routes.draw do
  # get 'static_pages/home'


  root 'static_pages#home'
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # user edit
  get 'users/edit', to: 'users#edit', as: 'edit_user'

  authenticated :user do
    root 'static_pages#home', as: :authenticated_root
  end

  unauthenticated do
    root 'static_pages#home', as: :unauthenticated_root
  end
  
  resources :categories
  
  resources :articles do 
    resources :comments, only: [:create]
  end

  resources :comments

  get 'contacts', to: 'contacts#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'users/show'
end

app/models/category.rb
class Category < ApplicationRecord
    # has_many :articles, dependent: :destroy
    # has_many :users, :through => :articles
    extend FriendlyId
    friendly_id :category_name, use: :slugged

    validates :category_name, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
    @flash_news = Article.joins(:category).order("articles.created_at DESC").limit(3).group("categories.id")
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.friendly.find(params[:id])
    @articles = Article.where(category_id: @category.id).order("created_at DESC")
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.id = SecureRandom.uuid

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:category_name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Category Name:</strong>
    <%= category.category_name %>
  </p>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <ul class="list-group">
        <% category.errors.each do |error| %>
          <li class="list-group-item"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div class="row">
      <div class="col-sm-12">
        <div class="form-group">
          <h2><%= form.label "Category name:" %></h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <div class="form-group">
          <%= form.text_field :category_name, style: "width: 100%; height: 48px; padding: 0 16px", placeholder: "Enter Category Name" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <div class="form-group">
          <%= link_to "Back to Categories", categories_path, class: "btn btn-lg font-weight-bold mt-3 float-left", style: "background-color: #032a63; color: #fff;font-size: 16px" %>
          <%= form.submit category.new_record? ? "Create Category" : "Save Category", class: "btn btn-lg font-weight-bold mt-3 float-right", style: "background-color: #032a63; color: #fff;font-size: 16px" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="content-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="card" data-aos="fade-up">
          <div class="card-body">
            <div class="aboutus-wrapper">
              <h1 class="text-center mb-5 text-uppercase">
                Edit Category
              </h1>
              <div class="row">
                <div class="col-lg-12 mb-5 mb-sm-2">
                  <%= render "form", category: @category %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="content-wrapper">
  <div class="container">
    <div class="row" data-aos="fade-up">
      <div class="col-lg-3 stretch-card grid-margin">
        <div class="card">
          <div class="card-body">
            <h2>Category</h2>
            <ul class="vertical-menu">
              <% @categories.each do |category| %>
                <li style="text-transform: capitalize;"><%= link_to category.category_name, category_path(category) %></li>
              <% end %>
            </ul>
            <% if user_signed_in? %>
              <%= link_to "New Category", new_category_path, class: "btn font-weight-bold", style: "background-color: #032a63; color: #fff; width: 100%; margin-top: 12%; font-size: 14px" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-lg-9 stretch-card grid-margin">
        <div class="card">
          <div class="card-body">
            <% @flash_news.each do |article| %>
              <div class="row">
                <div class="col-sm-4 grid-margin">
                  <div class="position-relative">
                    <div class="rotate-img">
                      <% if article.thumbnail.attached? %>
                        <%= link_to article_path(article) do %>
                          <%= image_tag article.thumbnail, class: "img-fluid", style: "border-radius: 4px" %>
                        <% end %>
                      <% end %>
                    </div>
                    <div class="badge-positioned badge badge-danger font-weight-bold text-capitalize">
                      <%= article.category.category_name %>
                    </div>
                  </div>
                </div>
                <div class="col-sm-8  grid-margin">
                  <h2>
                    <%= link_to article_path(article), class: "mb-2 font-weight-600", style: "text-decoration: none; color: #000" do %>
                      <% article.title.truncate(50) %>
                    <% end %>
                  </h2>
                  <div class="fs-13 mb-2">
                    <%= article.created_at.strftime("%B %d, %Y") %>
                  </div>
                  <p>
                    <%= link_to article_path(article), class: "text-dark mb-0", style: "text-decoration: none" do %>
                      <%= article.content.truncate(300) %>
                    <% end %>
                  </p>
                </div>
              </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="content-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="card" data-aos="fade-up">
          <div class="card-body">
            <div class="aboutus-wrapper">
              <h1 class="text-center mb-5 text-uppercase">
                New Category
              </h1>
              <div class="row">
                <div class="col-lg-12 mb-5 mb-sm-2">
                  <%= render "form", category: @category %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="content-wrapper">
  <div class="container">
    <div class="col-sm-12">
      <div class="card" data-aos="fade-up">
        <div class="card-body">
          <% if user_signed_in? %>
            <div class="float-right" style="display: flex;">
              <%= link_to "Edit", edit_category_path(@category), class: "btn btn-primary", style: "color: #fff; font-size: 16px; margin-right: 10px" %>
              <%# <%= button_to "Delete", category_path(@category), method: :delete, class: "btn btn-danger", style: "color: #fff; font-size: 16px" %>
            </div>
          <% end %>
          <div class="row">
            <div class="col-sm-12">
              <h1 class="font-weight-600 mb-4" style="text-transform: uppercase;">
                <%= @category.category_name %>
              </h1>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-8">
              <% @articles.each do |article| %>
                <div class="row">
                  <div class="col-sm-4 grid-margin">
                    <div class="rotate-img">
                      <% if article.thumbnail.attached? %>
                        <%= link_to article_path(article) do %>
                          <%= image_tag article.thumbnail, class: "img-fluid" %>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                  <div class="col-sm-8 grid-margin">
                    <h2>
                      <%= link_to article_path(article), class: "font-weight-600 mb-2", style: "color: #000; text-decoration: none;" do %>
                        <%= article.title.truncate(50) %>
                      <% end %>
                    </h2>
                    <p class="fs-13 text-muted mb-0">
                      <%= article.created_at.strftime("%B %d, %Y") %>
                    </p>
                    <p>
                      <%= link_to article_path(article), class: "fs-15", style: "color: #000; text-decoration: none;" do %>
                        <%= article.content.truncate(200) %>
                      <% end %>
                    </p>
                  </div>
                </div>
              <% end %>
            </div>
            <div class="col-lg-4">
              <h2 class="mb-4 text-primary font-weight-600">
                Latest news
              </h2>
              <% @articles.first(3).each do |article| %>
                <div class="row">
                  <div class="col-sm-12">
                    <div class="border-bottom pb-4 pt-4">
                      <div class="row">
                        <div class="col-sm-8">
                          <h5>
                            <%= link_to article_path(article), class: "font-weight-600 mb-1", style: "color: #000; text-decoration: none;" do %>
                              <%= article.title.truncate(30) %>
                            <% end %>
                          </h5>
                          <p class="fs-13 text-muted mb-0">
                            <%= article.created_at.strftime("%B %d, %Y") %>
                          </p>
                        </div>
                        <div class="col-sm-4">
                          <div class="rotate-img">
                            <% if article.thumbnail.attached? %>
                              <%= link_to article_path(article) do %>
                                <%= image_tag article.thumbnail, class: "img-fluid" %>
                              <% end %>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
              <div class="trending">
                <h2 class="mb-4 text-primary font-weight-600">
                  Trending
                </h2>
                <% @articles.first(3).each do |article| %>

                  <div class="mb-4">
                    <div class="rotate-img">
                      <% if article.thumbnail.attached? %>
                        <%= link_to article_path(article) do %>
                          <%= image_tag article.thumbnail, class: "img-fluid", style: "width: 100%; height: 100px; object-fit: cover;" %>
                        <% end %>
                      <% end %>
                    </div>
                    <h3>
                      <%= link_to article_path(article), class: "mt-3 font-weight-600", style: "color: #000; text-decoration: none;" do %>
                        <%= article.title.truncate(40) %>
                      <% end %>

                    </h3>
                    <p class="fs-13 text-muted mb-0">
                      <%= article.created_at.strftime("%B %d, %Y") %>
                    </p>
                  </div>

                <% end %>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>