config/routes.rb
Rails.application.routes.draw do
  # get 'static_pages/home'


  root 'static_pages#home'
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # user edit
  get 'users/edit', to: 'users#edit', as: 'edit_user'

  authenticated :user do
    root 'static_pages#home', as: :authenticated_root
  end

  unauthenticated do
    root 'static_pages#home', as: :unauthenticated_root
  end
  
  resources :categories
  
  resources :articles do 
    resources :comments, only: [:create]
  end

  resources :comments

  get 'contacts', to: 'contacts#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'users/show'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsWeb</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="shortcut icon" href="/assets/images/favicon.png"/>



  <%= javascript_importmap_tags %>
  <%= stylesheet_link_tag "css/style" %>
  <%= stylesheet_link_tag "vendors/mdi/css/materialdesignicons.min" %>
  <%= stylesheet_link_tag "vendors/aos/dist/aos.css/aos" %>


</head>

<body>


<header id="header">
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="navbar-top">
        <div class="d-flex justify-content-between align-items-center">
          <ul class="navbar-top-left-menu">
            <% if user_signed_in? %>
              <li class="nav-item">
                <p class="nav-link">Hello, <%= link_to current_user.email, users_show_path %></p>
              </li>
              <li class="nav-item">
                <p><%= link_to "LogOut", destroy_user_session_path, class: "nav-link", method: :delete %></p>
              </li>

            <% else %>

              <li class="nav-item">
                <p><%= link_to "LogIn", new_user_session_path, class: "nav-link" %></p>
              </li>
              <li class="nav-item">
                <p><%= link_to "SignUp", new_user_registration_path, class: "nav-link" %></p>
              </li>
            <% end %>
          </ul>
          <% if user_signed_in? %>
            <%= link_to "Create Article", new_article_path, class: "btn btn-light", style: "font-size: 16px" %>
          <% end %>
        </div>
      </div>
      <div class="navbar-bottom">
        <div class="d-flex justify-content-between align-items-center">
          <div>
            <a class="navbar-brand" href="/"
            ><img src="/assets/images/logo.svg" alt=""
              /></a>
          </div>
          <div>
            <button
              class="navbar-toggler"
              type="button"
              data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="navbar-toggler-icon"></span>
            </button>
            <div
              class="navbar-collapse justify-content-center collapse"
              id="navbarSupportedContent"
            >
              <ul
                class="navbar-nav d-lg-flex justify-content-between align-items-center"
              >
                <li>
                  <button class="navbar-close">
                    <i class="mdi mdi-close"></i>
                  </button>
                </li>
                <li class="nav-item active">
                  <%= link_to "Home", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Categories", categories_path, class: "nav-link" %>
                </li>
                <% Category.first(5).each do |category| %>
                  <li class="nav-item">
                    <%= link_to category.category_name, category_path(category), class: "nav-link" %>
                  </li>
                <% end %>
                <li class="nav-item">
                  <%= link_to "Contact", contacts_path, class: "nav-link" %>
                </li>
              </ul>
            </div>
          </div>
          <ul class="social-media">
            <li>
              <a href="#">
                <i class="mdi mdi-facebook"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="mdi mdi-youtube"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="mdi mdi-twitter"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</header>

<%= yield %>

<footer>
  <div class="footer-top">
    <div class="container">
      <div class="row">
        <div class="col-sm-5">
          <img src="/assets/images/logo.svg" class="footer-logo" alt=""/>
          <h5 class="font-weight-normal mt-4 mb-5">
            Newspaper is your news, entertainment, music fashion website. We
            provide you with the latest breaking news and videos straight from
            the entertainment industry.
          </h5>
          <ul class="social-media mb-3">
            <li>
              <a href="#">
                <i class="mdi mdi-facebook"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="mdi mdi-youtube"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="mdi mdi-twitter"></i>
              </a>
            </li>
          </ul>
        </div>
        <div class="col-sm-4">
          <h3 class="font-weight-bold mb-3">RECENT POSTS</h3>
          <div class="row">
            <div class="col-sm-12">
              <div class="footer-border-bottom pb-2">
                <div class="row">
                  <div class="col-3">
                    <img
                      src="/assets/images/dashboard/home_1.jpg"
                      alt="thumb"
                      class="img-fluid"
                      />
                  </div>
                  <div class="col-9">
                    <h5 class="font-weight-600">
                      Cotton import from USA to soar was American traders
                      predict
                    </h5>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <div class="footer-border-bottom pb-2 pt-2">
                <div class="row">
                  <div class="col-3">
                    <img
                      src="/assets/images/dashboard/home_2.jpg"
                      alt="thumb"
                      class="img-fluid"
                      />
                  </div>
                  <div class="col-9">
                    <h5 class="font-weight-600">
                      Cotton import from USA to soar was American traders
                      predict
                    </h5>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <div>
                <div class="row">
                  <div class="col-3">
                    <img
                      src="/assets/images/dashboard/home_3.jpg"
                      alt="thumb"
                      class="img-fluid"
                      />
                  </div>
                  <div class="col-9">
                    <h5 class="font-weight-600 mb-3">
                      Cotton import from USA to soar was American traders
                      predict
                    </h5>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <h3 class="font-weight-bold mb-3">CATEGORIES</h3>
          <div class="footer-border-bottom pb-2">
            <div class="d-flex justify-content-between align-items-center">
              <h5 class="mb-0 font-weight-600">Magazine</h5>
              <div class="count">1</div>
            </div>
          </div>
          <div class="footer-border-bottom pb-2 pt-2">
            <div class="d-flex justify-content-between align-items-center">
              <h5 class="mb-0 font-weight-600">Business</h5>
              <div class="count">1</div>
            </div>
          </div>
          <div class="footer-border-bottom pb-2 pt-2">
            <div class="d-flex justify-content-between align-items-center">
              <h5 class="mb-0 font-weight-600">Sports</h5>
              <div class="count">1</div>
            </div>
          </div>
          <div class="footer-border-bottom pb-2 pt-2">
            <div class="d-flex justify-content-between align-items-center">
              <h5 class="mb-0 font-weight-600">Arts</h5>
              <div class="count">1</div>
            </div>
          </div>
          <div class="pt-2">
            <div class="d-flex justify-content-between align-items-center">
              <h5 class="mb-0 font-weight-600">Politics</h5>
              <div class="count">1</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="d-sm-flex justify-content-between align-items-center">
            <div class="fs-14 font-weight-600">
              © 2023 All rights reserved.
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</footer>


<!-- partial -->
</div>
</div>
<!-- inject:js -->
<script src="/assets/vendors/js/vendor.bundle.base.js"></script>
<!-- endinject -->
<!-- plugin js for this page -->
<script src="/assets/vendors/aos/dist/aos.js/aos.js"></script>
<!-- End plugin js for this page -->
<!-- Custom js for this page-->
<script src="/assets/js/demo.js"></script>
<script src="/assets/js/jquery.easeScroll.js"></script>
<!-- End custom js for this page-->
</body>
</body>
</html>